# Generated by Django 5.1.5 on 2025-01-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('forecast_time', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('latitude', 'longitude', 'forecast_time'), name='unique_weather_record')],
            },
        ),
    ]
